//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 12:01:01 PM UTC 
//


package org.hibernate.boot.jaxb.hbm.spi;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import org.hibernate.cache.spi.access.AccessType;

public class Adapter2
    extends XmlAdapter<String, AccessType>
{


    public AccessType unmarshal(String value) {
        return (org.hibernate.boot.jaxb.hbm.internal.CacheAccessTypeConverter.fromXml(value));
    }

    public String marshal(AccessType value) {
        return (org.hibernate.boot.jaxb.hbm.internal.CacheAccessTypeConverter.toXml(value));
    }

}
